M48
; DRILL file {KiCad 9.0.6} date 2026-09-05T09:14:45+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-05T09:14:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C8.400
%
G90
G05
T1
X95.0Y-97.0
X132.0Y-60.0
X142.0Y-95.0
X160.0Y-60.0
T2
X80.0Y-80.0
X80.0Y-120.0
T3
X79.6Y-40.0
X79.6Y-160.0
X159.35Y-159.8
X159.6Y-40.0
M30
